// Generated by apply-carta.mjs. Which widths each carta image really has,
// so the runtime srcset never asks for a file that was never produced.
window.CARTA_WIDTHS = {
 "alitas-asiaticas": [
  480,
  768
 ],
 "alitas-garlic": [
  480,
  768
 ],
 "alitas-clasicas": [
  480,
  768
 ],
 "alitas-picantes": [
  480,
  768
 ],
 "arroz-especial": [
  480,
  768,
  1024
 ],
 "salsa-asiatica": [
  480,
  768,
  1024
 ],
 "baba-de-camello": [
  480,
  768,
  1024
 ],
 "boniato-rostizado": [
  480,
  768
 ],
 "bowl-chica-de-la-casa": [
  480,
  768,
  1024
 ],
 "chupachups": [
  480,
  768
 ],
 "costillar-mazorca": [
  480,
  768
 ],
 "crispy-piri": [
  480,
  768,
  1024
 ],
 "gambuenazos": [
  480,
  768,
  1024,
  1366,
  1600,
  1920
 ],
 "menu-gran-pack": [
  480,
  768,
  1024
 ],
 "salsa-limon": [
  480,
  768,
  1024
 ],
 "bites-de-mazorca": [
  480,
  768,
  1024
 ],
 "medio-pollo": [
  480,
  768
 ],
 "mousse-de-chocolate": [
  480,
  768,
  1024
 ],
 "nachetes": [
  480,
  768
 ],
 "salsa-naranja": [
  480,
  768,
  1024
 ],
 "menu-pack-familiar": [
  480,
  768,
  1024
 ],
 "pan-hogaza-entera": [
  480,
  768
 ],
 "patatas-fritas": [
  480,
  768,
  1024
 ],
 "patatas-asadas": [
  480,
  768
 ],
 "patatas-gozonas": [
  480,
  768,
  1024
 ],
 "pie-de-limon": [
  480,
  768,
  1024
 ],
 "feta-bowl": [
  480,
  768
 ],
 "piri-piri-original-burger": [
  480,
  768,
  1024
 ],
 "piripiri-bowl": [
  480,
  768,
  1024
 ],
 "salsa-piri-piri-dulce": [
  480,
  768,
  1024
 ],
 "salsa-piri-piri-fuerte": [
  480,
  768,
  1024
 ],
 "menu-piri-piri-para-2": [
  480,
  768,
  1024
 ],
 "salsa-piri-piri-suave": [
  480,
  768,
  1024
 ],
 "menu-pollo-acompanamiento": [
  480,
  768,
  1024
 ],
 "pollo-entero": [
  480,
  768
 ],
 "salchicha-criolla": [
  480,
  768
 ],
 "gozadera-extra": [
  480,
  768,
  1024
 ],
 "menu-single": [
  480,
  768,
  1024
 ],
 "special-burger": [
  480,
  768,
  1024
 ],
 "tarta-de-queso": [
  480,
  768,
  1024
 ],
 "tenders": [
  480,
  768
 ],
 "tequenos": [
  480,
  768,
  1024
 ],
 "truffa-burger": [
  480,
  768,
  1024
 ]
};

// Width-aware srcset. carta.html and carta-item.html delegate to these so a
// dish whose master was only 928px never gets asked for a 1600w file.
window.CARTA_SRCSET = (function () {
  var SIZED = /[/](\d+)w[/](.+?)_(\d+)w[.]/;
  function parse(p) {
    var m = p && p.match(SIZED);
    return m && m[1] === m[3] ? { w: +m[1], base: m[2] } : null;
  }
  function avail(p) {
    var i = parse(p);
    return i && window.CARTA_WIDTHS ? window.CARTA_WIDTHS[i.base] || null : null;
  }
  function widthVariant(p, w) {
    var i = parse(p);
    if (!i) return p;
    var a = avail(p), use = w;
    if (a && a.length) {
      var fit = a.filter(function (x) { return x <= w; });
      use = fit.length ? fit[fit.length - 1] : a[0];
    }
    return p.split("/" + i.w + "w/").join("/" + use + "w/")
            .split("_" + i.w + "w.").join("_" + use + "w.");
  }
  function srcsetFor(p, widths) {
    if (!parse(p)) return "";
    var a = avail(p);
    var use = a ? widths.filter(function (w) { return a.indexOf(w) >= 0; }) : widths;
    return use.map(function (w) { return widthVariant(p, w) + " " + w + "w"; }).join(", ");
  }
  return { widthVariant: widthVariant, srcsetFor: srcsetFor };
})();
